language: c

os:
        - linux

before_install:
        - export HOSTCC=gcc
        - sudo apt-get -qq update
        - sudo apt-get install flex bison gperf libncurses-dev pkg-config

compiler:
        - clang
        - gcc

script: make defconfig && make
