language: c
  matrix:
    include:
      - os: linux
        sudo: required
        env: TOXENV=clang HOSTCC=clang CC=clang
      - os: osx
        language: generic
        env: TOKENV=osx-clang HOSTCC=clang CC=clang

addons:
  apt:
    packages:
      - graphviz
      - flex 
      - bison 
      - gperf 
      - libncurses-dev 
      - pkg-config        

before install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install flex ; fi

script: 
- uname -a
- make defconfig
- make V=1
