language:
- c
- java
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - flex
    - bison
    - gperf
    - pkg-config
    - binutils-mingw-w64-i686
    - gcc-mingw-w64-i686
    - binutils-mingw-w64
    - gcc-mingw-w64
    - gcc-arm-linux-gnueabihf
    - gcc-arm-linux-gnueabi
    - binutils-arm-linux-gnueabi      
    - binutils-arm-linux-gnueabihf
    - libc6-dev-s390x-cross
    - libc6-dev
    - gcc-5-cross
    - libgcc-5-cross
    - wine
env:
  global:
  - BUILD_BRANCH=$TRAVIS_BRANCH
  - BUILD_ID=$TRAVIS_BUILD_NUMBER

matrix:
  include:
  - compiler: gcc
    os: linux
    env: BUILD_DEPLOY=1 BUILD_TARGET=linux BUILD_ARCH=x86_64
  - compiler: gcc
    os: linux
    env: BUILD_DEPLOY=0 BUILD_TARGET=linux BUILD_ARCH=s390x
  - compiler: gcc
    os: linux
    env: BUILD_DEPLOY=0 BUILD_TARGET=linux BUILD_ARCH=arm
  - compiler: gcc
    os: linux
    env: BUILD_DEPLOY=1 BUILD_TARGET=win32 BUILD_ARCH=x86
  - compiler: gcc
    os: linux
    env: BUILD_DEPLOY=1 BUILD_TARGET=win64 BUILD_ARCH=x86_64
  - compiler: clang
    os: linux
    env: BUILD_DEPLOY=0 BUILD_TARGET=linux BUILD_ARCH=x86_64
  - compiler: gcc
    os: osx
    env: BUILD_DEPLOY=1 BUILD_TARGET=osx   BUILD_ARCH=x86_64 OS_VERSION="10.9"
  - compiler: clang
    os: osx
    env: BUILD_DEPLOY=0 BUILD_TARGET=osx BUILD_ARCH=x86_64 OS_VERSION="10.9"
  - compiler: clang
    os: osx
    env: BUILD_DEPLOY=1 BUILD_TARGET=osx BUILD_ARCH=x86_64 OS_VERSION="10.11"
    osx_image: xcode7.3
  - compiler: clang
    os: osx
    env: BUILD_DEPLOY=0 BUILD_TARGET=osx BUILD_ARCH=x86_64 OS_VERSION="10.11"
    osx_image: xcode7.2
  - compiler: clang
    os: osx
    env: BUILD_DEPLOY=1 BUILD_TARGET=osx BUILD_ARCH=x86_64 OS_VERSION="10.10"
    osx_image: xcode7.1
  - compiler: clang
    os: osx
    env: BUILD_DEPLOY=0 BUILD_TARGET=osx BUILD_ARCH=x86_64 OS_VERSION="10.10"
    osx_image: xcode7
  - compiler: clang
    os: osx
    env: BUILD_DEPLOY=0 BUILD_TARGET=osx BUILD_ARCH=x86_64 OS_VERSION="10.10"
    osx_image: beta-xcode6.4
  - compiler: clang
    os: osx
    env: BUILD_DEPLOY=0 BUILD_TARGET=osx BUILD_ARCH=x86_64 OS_VERSION="10.9"
    osx_image: beta-xcode6.2
allow_failures:
  - compiler: gcc
    env: BUILD_DEPLOY=0 BUILD_TARGET=linux BUILD_ARCH=s390x
  - compiler: gcc
    env: BUILD_DEPLOY=0 BUILD_TARGET=linux BUILD_ARCH=arm
before_deploy:
- export BUILD_ARCHIVE=kbuild-$BUILD_MAJOR.$BUILD_MINOR.$BUILD_REVISION-$BUILD_OS_NAME-$BUILD_OS_ARCH-$BUILD_OS_RELEASE.tar.gz
- ./scripts/travis/archive.sh $BUILD_ARCHIVE
before_install:
  - source ./scripts/travis/before_install.sh

script:
- uname -a
- make defconfig
- make V=1
- cat ./obj/.config
- file ./obj/sysconfig
- $OS_EXEC ./obj/sysconfig
notifications:
  on_success: never
  on_failure: never
  email: false
deploy:
  provider: releases
  api_key:
    secure: OfYWkedmramdd2ML/dL+lQ+rYWLNaLWy1HfMxxyKwOZThIgWekxhy9EeqEVAisGXBU6qEe9FpsrOi3EUb3OwUNLmKz5b46fs8DpcjsFTKEGhkpXPDJJiwf5Sk0kOUvQp34euv5tBzMFrDxcB/vOpgFMjvWVx5j7BM+e8X0t3RMJANp7vEK5v71KjbbvERZTVaVAeFLrC5vcqcbwad/0fVGJYcvDXRmzs0W8Vc9v8OznfhbwtCj0f8HyfYoPkUXudzDYyDGoGbadKrbeLYYx/fQqlCeLxxLsfjTStYe3fGer2pPUJIBHUL3vvQRhBNr4t89zVvkUcmg7ems2/SG1gCeIX1E1WbnMxpNd98v1CP4Ku7LfJTkpjOv+0FWCbKj32AtoklOMzU8FQw/X/Ys4+Qpo42v4u4NVzWcDTR7y7TQcnOqqmhBbU5GJs+xz3p1bDm0Q2aOwqUGo7OACQ4my5xjjPLCNrV5/FFv3GYn4XutHZjvyLPie7AMArggITSTPZEMn3SYYdxyDp+VloW2vHfI3jByDFwjDGMr3TN6dZyGXXI9DWXeqizVKG5t9P3zc6Vda+VLCaq3AC2vl57RSooDEg3m3kPEEuI+P2omnHuCgAXuHVQaxw5aji+fk72G6zYuTcAMhJJQujWFIQxRtuSZwDZc7M7DOpg5xE7dTfrVA=
  file_glob: true
  file: "$BUILD_ARCHIVE"
  skip_cleanup: true
  on:
    tags: yes
    repo: n13l/kbuild
    condition: "$BUILD_DEPLOY = 1"
