language: c

os:
        - linux
        - osx

before_install:
        - sudo apt-get -qq update
        - sudo apt-get install flex bison gperf ncurses

compiler:
        - clang
        - gcc

script: make defconfig && make
