sudo: required
#dist: trusty
language:
- c
- java
- android
jdk:
- oraclejdk8
android:
  components:
  - platform-tools
  - tools
# The BuildTools version used by your project
  - build-tools-19.1.0
# The SDK version used to compile your project
  - android-19
# Additional components
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-19
# Specify at least one system image,
# if you need to run emulator(s) during your tests
  - sys-img-armeabi-v7a-android-19
  - sys-img-x86-android-17
addons:
  apt:
    packages:
    - flex
    - bison
    - gperf
    - pkg-config
env:
  global:
  - BUILD_BRANCH=$TRAVIS_BRANCH
  - BUILD_ID=$TRAVIS_BUILD_NUMBER

matrix:
  include:
  - compiler: gcc
    os: linux
    env: BUILD_DEPLOY=1 BUILD_TARGET=linux BUILD_ARCH=x86_64
  - compiler: gcc
    dist: trusty
    os: linux
    env: BUILD_DEPLOY=0 BUILD_TARGET=linux BUILD_ARCH=s390x
  - compiler: gcc
    dist: trusty
    os: linux
    env: BUILD_DEPLOY=0 BUILD_TARGET=linux BUILD_ARCH=powerpc64
  - compiler: gcc
    os: linux
    env: BUILD_DEPLOY=1 BUILD_TARGET=linux BUILD_ARCH=arm32
    addons:
      apt:
        packages: &armv7_unknown_linux_gnueabihf
        # Cross compiler and cross compiled C libraries
        - flex
        - bison
        - gperf
        - pkg-config
        - gcc-arm-linux-gnueabihf
        - libc6-armhf-cross
        - libc6-dev-armhf-cross
        # Transparent emulation
        - qemu-user-static
        - binfmt-support
  - compiler: gcc
    dist: trusty
    os: linux
    env: BUILD_DEPLOY=1 BUILD_TARGET=linux BUILD_ARCH=arm64
    addons:
      apt:
        packages: &armv7_unknown_linux_gnueabihf
        # Cross compiler and cross compiled C libraries
        - flex
        - bison
        - gperf
        - pkg-config
        - gcc-aarch64-linux-gnu
        - libc6-arm64-cross 
        - libc6-dev-arm64-cross 
        # Transparent emulation
        - qemu-user-static
        - binfmt-support
  - compiler: gcc
    os: linux
    env: BUILD_DEPLOY=1 BUILD_TARGET=win32 BUILD_ARCH=x86_32
    addons:
      sources:
        - debian-sid
      apt:
        packages:
        - flex
        - bison
        - gperf
        - pkg-config
        - binutils-mingw-w64-i686
        - gcc-mingw-w64-i686
        - wine
  - compiler: gcc
    os: linux
    env: BUILD_DEPLOY=1 BUILD_TARGET=win64 BUILD_ARCH=x86_64
    addons:
      sources:
        - debian-sid
      apt:
        packages:
        - flex
        - bison
        - gperf
        - pkg-config
        - binutils-mingw-w64
        - gcc-mingw-w64
        - wine
  - compiler: clang
    os: linux
    env: BUILD_DEPLOY=0 BUILD_TARGET=linux BUILD_ARCH=x86_64
#  - compiler: clang
#    os: osx
#    env: BUILD_DEPLOY=1 BUILD_TARGET=osx BUILD_ARCH=x86_64 OS_VERSION="10.11"
#    osx_image: xcode8
#  - compiler: clang
#    os: osx
#    env: BUILD_DEPLOY=0 BUILD_TARGET=osx BUILD_ARCH=x86_64 OS_VERSION="10.12"
#    osx_image: xcode8.2
  - compiler: clang
    os: osx
    env: BUILD_DEPLOY=0 BUILD_TARGET=osx BUILD_ARCH=x86_64 OS_VERSION="10.9"
    osx_image: xcode8.1
  allow_failures:
  - compiler: gcc
    os: linux
    env: BUILD_DEPLOY=0 BUILD_TARGET=linux BUILD_ARCH=powerpc64
  - compiler: gcc
    os: linux
    env: BUILD_DEPLOY=0 BUILD_TARGET=linux BUILD_ARCH=s390x
  - compiler: gcc
    os: linux
    env: BUILD_DEPLOY=1 BUILD_TARGET=linux BUILD_ARCH=arm32
  - compiler: gcc
    os: linux
    env: BUILD_DEPLOY=1 BUILD_TARGET=linux BUILD_ARCH=arm64
#  - compiler: gcc
#    os: linux
#    env: BUILD_DEPLOY=1 BUILD_TARGET=win32 BUILD_ARCH=x86_32
#  - compiler: gcc
#    os: linux
#    env: BUILD_DEPLOY=1 BUILD_TARGET=win64 BUILD_ARCH=x86_64
 
before_deploy:
- export BUILD_ARCHIVE=kbuild-$BUILD_MAJOR.$BUILD_MINOR.$BUILD_REVISION-$BUILD_OS_NAME-$BUILD_OS_ARCH-$BUILD_OS_RELEASE.tar.gz
- ./scripts/travis/archive.sh $BUILD_ARCHIVE
before_install:
  - source ./scripts/travis/before_install.sh
script:
#- shell_session_update() { :; } # workarround mac os build bug
- export PATH=$PWD/local/bin:$PATH
- uname -a
- make defconfig
- cat ./obj/.config
- make
- file ./obj/test/perf/alloc
- $OS_EXEC ./obj/test/perf/alloc
- $OS_EXEC ./obj/test/sort
notifications:
  on_success: never
  on_failure: never
  email: false
deploy:
  provider: releases
  prerelease: true
  draft: true
  api_key:
    secure: 
  file_glob: true
  file: "$BUILD_ARCHIVE"
  skip_cleanup: true
  on:
    tags: yes
    repo: n13l/kbuild
    condition: "$BUILD_DEPLOY = 1"
