#!/bin/sh
#
# Generate modules/built-in.h that #includes headers from every
# statically-configured (=y) module directory.
#
# The script parses modules/Kbuild to discover which CONFIG_* symbols
# map to which subdirectories, then checks include/config/auto.conf
# (or .config) to see which symbols are set to "y".  For each match
# it emits an #include for every .h file found directly in that
# module directory.
#
# Usage: gen-builtin-modules.sh <srctree> <objtree>

srctree="${1:-.}"
objtree="${2:-$srctree/obj}"
output="$objtree/modules/built-in.h"
kbuild="$srctree/modules/Kbuild"
autoconf="$objtree/include/config/auto.conf"

if [ ! -f "$autoconf" ]; then
	autoconf="$objtree/.config"
fi

if [ ! -f "$autoconf" ]; then
	exit 0
fi

if [ ! -f "$kbuild" ]; then
	exit 0
fi

mkdir -p "$(dirname "$output")"

tmp="$output.tmp"

cat > "$tmp" <<'EOF'
/* Auto-generated by scripts/gen-builtin-modules.sh -- do not edit */
#ifndef __MODULES_BUILT_IN_H__
#define __MODULES_BUILT_IN_H__

EOF

seen=""

grep '^obj-\$(CONFIG_' "$kbuild" | while IFS= read -r line; do
	sym=$(echo "$line" | sed 's/.*\$(CONFIG_\([A-Za-z0-9_]*\)).*/\1/')
	dir=$(echo "$line" | sed 's/.*+= *//; s/ *$//')

	# Skip if we already processed this directory
	case " $seen " in
		*" $dir "*) continue ;;
	esac

	if grep -q "^CONFIG_${sym}=y" "$autoconf"; then
		moddir="$srctree/modules/$dir"
		if [ -d "$moddir" ]; then
			for hdr in "$moddir"*.h; do
				[ -f "$hdr" ] || continue
				relpath=$(echo "$hdr" | sed "s|^$srctree/||")
				printf '#include <%s>\n' "$relpath" >> "$tmp"
			done
		fi
		seen="$seen $dir"
	fi
done

cat >> "$tmp" <<'EOF'

#endif /* __MODULES_BUILT_IN_H__ */
EOF

if [ -f "$output" ] && cmp -s "$tmp" "$output" 2>/dev/null; then
	rm -f "$tmp"
else
	mv -f "$tmp" "$output"
fi
