#!/bin/sh
#
# Generate modules/built-in.h that #includes built-in.h headers from every
# statically-configured (=y) module directory.
#
# The script discovers module directories by scanning for built-in.h files
# anywhere under modules/, then checks modules/Kbuild and
# include/config/auto.conf to determine which are configured as built-in
# (=y).  No module paths are hardcoded in this script.
#
# Usage: gen-builtin-modules.sh <srctree> <objtree>

srctree="${1:-.}"
objtree="${2:-$srctree/obj}"

# The module tree may live under a package subdirectory relative to srctree
# (CRYPTO_DIR, e.g. vendor/crypto when hosted, "." when standalone). The
# emitted #include paths stay srctree-relative so they resolve against -I<root>.
case "${CRYPTO_DIR:-.}" in
	.|"") modrel="modules" ;;
	*)    modrel="${CRYPTO_DIR}/modules" ;;
esac

output="$objtree/modules/built-in.h"
kbuild="$srctree/$modrel/Kbuild"
autoconf="$objtree/include/config/auto.conf"

if [ ! -f "$autoconf" ]; then
	autoconf="$objtree/.config"
fi

if [ ! -f "$autoconf" ]; then
	exit 0
fi

mkdir -p "$(dirname "$output")"

tmp="$output.tmp"

cat > "$tmp" <<'EOF'
/* Auto-generated by scripts/gen-builtin-modules.sh -- do not edit */
#ifndef __MODULES_BUILT_IN_H__
#define __MODULES_BUILT_IN_H__

EOF

# Discover modules by finding built-in.h in any subdirectory of the module tree.
find "$srctree/$modrel" -name 'built-in.h' -type f 2>/dev/null | sort | \
while IFS= read -r hdr; do
	relpath=$(echo "$hdr" | sed "s|^$srctree/||")
	# Directory relative to the module tree, with trailing slash
	reldir="$(dirname "$hdr" | sed "s|^$srctree/$modrel/||")/"

	# Look up CONFIG symbols that reference this directory in Kbuild.
	# Check both the top-level modules/Kbuild and the parent Kbuild
	# (e.g., modules/digest/Kbuild for modules/digest/sha3-ossl/).
	moddir="$(dirname "$hdr")"
	basename="$(basename "$moddir")/"
	parent_kbuild="$(dirname "$moddir")/Kbuild"

	included=0
	for kb in "$kbuild" "$parent_kbuild"; do
		if [ "$included" = 0 ] && [ -f "$kb" ]; then
			for sym in $(grep "+= *${basename}" "$kb" | \
				sed 's/.*\$(CONFIG_\([A-Za-z0-9_]*\)).*/\1/'); do
				if [ "$included" = 0 ] && \
				   grep -q "^CONFIG_${sym}=y" "$autoconf"; then
					printf '#include <%s>\n' "$relpath" >> "$tmp"
					included=1
				fi
			done
		fi
	done
done

cat >> "$tmp" <<'EOF'

#endif /* __MODULES_BUILT_IN_H__ */
EOF

if [ -f "$output" ] && cmp -s "$tmp" "$output" 2>/dev/null; then
	rm -f "$tmp"
else
	mv -f "$tmp" "$output"
fi
