obj-m := entry.o
entry-objs := dummy.o

lib                := dummy
libname            := libmodule-$(lib)-$(PACKAGEVERSION)

always             += $(if $(CONFIG_MODULES),$(libname).$(so),)

#swflags           := -debug-module 1

libdummy-dirs := generic mem net crypto sys/$(PLATFORM)
libdummy-objs := $(patsubst %,%/built-in.o, $(libdummy-dirs)) modules/dummy/entry.o
libdummy-libs := $(patsubst %,%/lib.a, $(libs-y))
libdummy-all  := $(libdummy-objs) $(libdummy-libs) $(KBUILD_LIBS)

$(obj)/$(libname).$(so): $(libdummy-objs) $(libdummy-libs)
	$(call if_changed,$(libname).$(so))

quiet_cmd_$(libname).$(so) = LD [M]  $@
	cmd_$(libname).$(so) = $(CC) $(LDFLAGS) $(SHLIB_LDFLAGS) -o $@ \
	                             $(libdummy-all)

PHONY += $(libdummy-dirs)
$(libdummy-dirs): scripts_basic
	$(Q)$(MAKE) $(build)=$@
clean-files  += $(libname).$(so) $(libname).jar


